# Generated by Django 5.0.7 on 2024-08-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playergame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='managerial_career',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='youth_career',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='club_career',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='intl_career',
            field=models.JSONField(),
        ),
    ]
