# Generated by Django 5.0.6 on 2024-08-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playergame', '0002_player_age_player_managerial_career_player_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('player_pairs', models.JSONField()),
                ('precomputed_links', models.JSONField()),
            ],
        ),
    ]
