# Generated by Django 5.0.6 on 2024-08-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playergame', '0003_dailygame'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygame',
            name='link_types',
            field=models.JSONField(default=list),
        ),
    ]
