# Generated by Django 5.0.6 on 2024-08-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playergame', '0004_dailygame_link_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygame',
            name='link_types',
            field=models.JSONField(),
        ),
    ]
