# Generated by Django 5.0.6 on 2024-09-02 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playergame', '0005_alter_dailygame_link_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('current_round', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('lives_remaining', models.IntegerField(default=3)),
                ('start_player', models.CharField(max_length=100)),
                ('end_player', models.CharField(max_length=100)),
                ('link_type', models.CharField(max_length=20)),
                ('intermediate_players', models.JSONField(default=list)),
                ('previous_guesses', models.JSONField(default=list)),
                ('round_scores', models.JSONField(default=list)),
                ('is_game_won', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
