# Generated by Django 5.0.6 on 2024-09-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playergame', '0006_gamesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='user',
        ),
    ]
