# Generated by Django 5.0.6 on 2024-09-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playergame', '0007_remove_gamesession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='round_data',
            field=models.JSONField(default=list),
        ),
    ]
