# Generated by Django 5.0.7 on 2024-09-09 02:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playergame', '0016_alter_gamesession_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='last_played_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
